name: Portfolio

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: rm -rf dist/*

      - name: Build project
        run: npm run build

      - name: List contents of dist  # Перевіряємо виведення директорії dist
        run: ls -la dist

      - name: List contents of dist  # Перевіряємо виведення директорії dist
        run: find dist -type l

      - name: List contents of dist  # Перевіряємо виведення директорії dist
        run: du -sh dist

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: artifffact
          path: dist

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: artifffact
          
