name: Portfolio

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: rm -rf dist/*

      - name: Build project
        run: npm run build

      - name: List contents of dist  # Перевіряємо виведення директорії dist
        run: ls -la dist

      - name: List contents of dist  # Перевіряємо виведення директорії dist
        run: find dist -type l

      - name: List contents of dist  # Перевіряємо виведення директорії dist
        run: du -sh dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          
